difference(){
    cube([35,33,7]);
    translate([10,0,0]){
        difference(){
            translate([3.5,6.5,4]){
                cylinder(3,d=1.6,$fn=16);
            }
        }
    }
    translate([10,33,0]){
        difference(){
            translate([3.5,-6.5,4]){
                cylinder(3,d=1.6,$fn=16);
            }
        }
    }
}